### ISSUE TITLE
haorooms js局部打印案例

### ISSUE THREAD

**Issue by treemoons** [treemoons/treemoons.github.io#2]
https://treemoons.github.io/

**Comment by treemoons** [comment]
```js
function test(paramater){
console.log('this is a markdown test.')
}
```

**Comment by treemoons** [comment]
THE LATEST NEWS IS UP TO TOP!

**Comment by ghost** [comment]
yes ,just a news welocom



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年7月22日(星期五) 下午5:26
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [treemoons/treemoons.github.io] haorooms js局部打印案例 (Issue #2)





 
THE LATEST NEWS IS UP TO TOP!
